### ISSUE TITLE
pycparser version?

### ISSUE THREAD

**Issue by ib00** [CudaWrangler/cuew#10]
What version of pycparser is 'cuew_gen.py' using?

I am getting some errors with the latest version of pycparser when trying to
generate files.

**Comment by sergeyvfx** [comment]
I am using the python3-pycparser package from the current Debian testing, which is on version 2.21-1.

What I've noticed is that the newer CUDA toolkit headers have more tricky syntax than what the initial version of the wrangler generator was dealing with. I've committed some fixes which seems to work here. Give them a whirl!

**Comment by ib00** [comment]
Thanks for looking into this.

I have tracked the particular error down to the following:

typedef struct CUlaunchAttribute_st {
    CUlaunchAttributeID id;
    char pad[8 - sizeof(CUlaunchAttributeID)];
    CUlaunchAttributeValue value;
} CUlaunchAttribute;

'cuew_gen.py' can't properly parse 'char pad[8 - sizeof(CUlaunchAttributeID)];'
which causes a problem on line 116 in 'cuew_gen.py' since the array dimension now
is a BinaryOp and not a Constant.

**Comment by sergeyvfx** [comment]
Just to confirm, does the issue still happen after changes I've made in 476e8795c32 ?

**Comment by ib00** [comment]
Just checked and your fix (in your fork) solves it. Thank you very much!

**Comment by sergeyvfx** [comment]
No problem, you're welcome!
Will consider this issue resolved now. But feel free to submit a new one if there is still something we're missing.
